---

include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v0.0.1"
    file:
      # TODO: Sphinx docs inherits a stage definition from upstream,
      # has to be included before our default stages to avoid trouble.
      - "jobs/sphinx-docs.yaml"
      - "defaults/souvap-workflow.yaml"
      - "defaults/stages.yaml"
      - "templates/kaniko.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/lint-pre-commit.yaml"

.kaniko_no_sock:
  extends: .kaniko
  before_script:
    # The GitLab runner mounts the Docker socket into /var/run.
    # Kaniko either ignores /var/run (default), or the socket ends up in the tarball.
    # We unmount the socket here, and later use `--ignore-var-run=false` to have a
    # regular /var/run directory in the final image.
    - "umount /var/run/docker.sock"
    - "rm -rf /var/run"

build-ucs-base-50X-matrix:
  stage: build
  extends: .kaniko_no_sock
  needs: []
  parallel:
    matrix:
      - UCS_VERSION:
          - 500
          - 501
          - 502
          - 503
          - 504
          - 505
  variables:
    KANIKO_BUILD_CONTEXT: "docker"
    APT_REPOSITORY: "http://updates.software-univention.de/"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-${UCS_VERSION}"
    KANIKO_ARGS:
      --ignore-var-run=false
      --build-arg UCS_VERSION=${UCS_VERSION}
      --build-arg APT_REPOSITORY=${APT_REPOSITORY}
      --target final


test-ucs-base-usage-example:
  stage: build
  extends: .kaniko_no_sock
  needs:
    - job: build-ucs-base-50X-matrix
      artifacts: true
  parallel:
    matrix:
      - UCS_VERSION:
          - 500
          - 501
          - 502
          - 503
          - 504
          - 505
  variables:
    KANIKO_BUILD_CONTEXT: "docker"
    DOCKERFILE_PATH: "docker/Dockerfile.usage-example"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-usage-example"
    KANIKO_CACHE_ARGS: ""
    KANIKO_ARGS: >-
      --no-push
      --build-arg UCS_BASE_IMAGE_TAG=${BUILD_VERSION}
      --build-arg UCS_VERSION=${UCS_VERSION}


build-ucs-base-dev-50X-matrix:
  stage: build
  extends: .kaniko_no_sock
  needs: []
  parallel:
    matrix:
      - UCS_VERSION:
          - 500
          - 501
          - 502
          - 503
          - 504
          - 505
  variables:
    APT_REPOSITORY: "http://updates.knut.univention.de/"
    KANIKO_BUILD_CONTEXT: "docker"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-dev-${UCS_VERSION}"
    KANIKO_ARGS:
      --ignore-var-run=false
      --build-arg UCS_VERSION=${UCS_VERSION}
      --build-arg APT_REPOSITORY=${APT_REPOSITORY}
      --target dev

test-ucs-base-dev-usage-example:
  stage: build
  extends: .kaniko_no_sock
  needs:
    - job: build-ucs-base-dev-50X-matrix
      artifacts: true
  parallel:
    matrix:
      - UCS_VERSION:
          - 500
          - 501
          - 502
          - 503
          - 504
          - 505
  variables:
    KANIKO_BUILD_CONTEXT: "docker"
    DOCKERFILE_PATH: "docker/dev.Dockerfile.usage-example"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-dev-usage-example"
    KANIKO_CACHE_ARGS: ""
    KANIKO_ARGS:
      --no-push
      --build-arg UCS_BASE_IMAGE_TAG=${BUILD_VERSION}
      --build-arg UCS_VERSION=${UCS_VERSION}

build-ucs-base-510:
  stage: build
  extends: .kaniko_no_sock
  needs: []
  variables:
    UCS_VERSION: 510
    APT_REPOSITORY: "http://updates-test.software-univention.de/"
    KANIKO_BUILD_CONTEXT: "docker"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-${UCS_VERSION}"
    KANIKO_ARGS:
      --ignore-var-run=false
      --build-arg UCS_VERSION=${UCS_VERSION}
      --build-arg APT_REPOSITORY=${APT_REPOSITORY}
      --target final

build-ucs-base-520:
  stage: build
  extends: .kaniko_no_sock
  needs: []
  variables:
    UCS_VERSION: 520
    APT_REPOSITORY: "http://updates-test.software-univention.de/"
    KANIKO_BUILD_CONTEXT: "docker"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-${UCS_VERSION}"
    KANIKO_ARGS:
      --dockerfile usr-merge.Dockerfile
      --ignore-var-run=false
      --build-arg UCS_VERSION=${UCS_VERSION}
      --build-arg APT_REPOSITORY=${APT_REPOSITORY}
      --target final

test-ucs-base-5X0-usage-example:
  stage: build
  extends: .kaniko_no_sock
  needs:
    - job: build-ucs-base-510
      artifacts: true
    - job: build-ucs-base-520
      artifacts: true
  parallel:
    matrix:
      - UCS_VERSION:
          - 510
          - 520
  variables:
    KANIKO_BUILD_CONTEXT: "docker"
    DOCKERFILE_PATH: "docker/Dockerfile.usage-example"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-usage-example"
    KANIKO_CACHE_ARGS: ""
    KANIKO_ARGS:
      --no-push
      --build-arg UCS_BASE_IMAGE_TAG=${BUILD_VERSION}
      --build-arg UCS_VERSION=${UCS_VERSION}

build-ucs-base-dev-510:
  stage: build
  extends: .kaniko_no_sock
  needs: []
  variables:
    UCS_VERSION: 510
    APT_REPOSITORY: "https://updates-test.software-univention.de/"
    KANIKO_BUILD_CONTEXT: "docker"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-dev-${UCS_VERSION}"
    KANIKO_ARGS:
      --ignore-var-run=false
      --build-arg UCS_VERSION=${UCS_VERSION}
      --build-arg APT_REPOSITORY=${APT_REPOSITORY}
      --target dev

build-ucs-base-dev-520:
  stage: build
  extends: .kaniko_no_sock
  needs: []
  variables:
    UCS_VERSION: 520
    APT_REPOSITORY: "https://updates-test.software-univention.de/"
    KANIKO_BUILD_CONTEXT: "docker"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-dev-${UCS_VERSION}"
    KANIKO_ARGS:
      --dockerfile usr-merge.Dockerfile
      --ignore-var-run=false
      --build-arg UCS_VERSION=${UCS_VERSION}
      --build-arg APT_REPOSITORY=${APT_REPOSITORY}
      --target dev

test-ucs-base-dev-5X0-usage-example:
  stage: build
  extends: .kaniko_no_sock
  needs:
    - job: build-ucs-base-dev-510
      artifacts: true
    - job: build-ucs-base-dev-520
      artifacts: true
  parallel:
    matrix:
      - UCS_VERSION:
          - 510
          - 520
  variables:
    KANIKO_BUILD_CONTEXT: "docker"
    DOCKERFILE_PATH: "docker/dev.Dockerfile.usage-example"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-usage-example"
    KANIKO_CACHE_ARGS: ""
    KANIKO_ARGS:
      --no-push
      --build-arg UCS_BASE_IMAGE_TAG=${BUILD_VERSION}
      --build-arg UCS_VERSION=${UCS_VERSION}

changelog:
  image:
    name: orhunp/git-cliff:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: clone # clone entire repo instead of reusing workspace
    GIT_DEPTH: 0 # avoid shallow clone to give cliff all the info it needs
  stage: package
  script:
    - git-cliff -r . > CHANGELOG.md
  artifacts:
    paths:
      - CHANGELOG.md

release:
  # TODO: Make a base image for this tool
  image: "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:18-buster-slim"
  stage: package
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/changelog conventional-changelog-conventionalcommits
  script:
    - semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

...
