---

include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v0.0.1"
    file:
      # TODO: Sphinx docs inherits a stage definition from upstream,
      # has to be included before our default stages to avoid trouble.
      - "jobs/sphinx-docs.yaml"
      - "defaults/souvap-workflow.yaml"
      - "defaults/stages.yaml"
      - "templates/kaniko.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/lint-pre-commit.yaml"


build-ucs-base-50X-matrix:
  stage: build
  extends: .kaniko
  needs: []
  parallel:
    matrix:
      - UCS_VERSION:
          - 500
          - 501
          - 502
          - 503
          - 504
          - 505
  variables:
    KANIKO_BUILD_CONTEXT: "docker"
    APT_REPOSITORY: "http://updates.software-univention.de/"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-${UCS_VERSION}"
    KANIKO_ARGS:
      --build-arg UCS_VERSION=${UCS_VERSION}
      --build-arg APT_REPOSITORY=${APT_REPOSITORY}
      --target final


test-ucs-base-usage-example:
  stage: build
  extends: .kaniko
  needs:
    - job: build-ucs-base-50X-matrix
      artifacts: true
  parallel:
    matrix:
      - UCS_VERSION:
          - 500
          - 501
          - 502
          - 503
          - 504
          - 505
  variables:
    KANIKO_BUILD_CONTEXT: "docker"
    DOCKERFILE_PATH: "docker/Dockerfile.usage-example"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-usage-example"
    KANIKO_CACHE_ARGS: ""
    KANIKO_ARGS: >-
      --no-push
      --build-arg UCS_BASE_IMAGE_TAG=${BUILD_VERSION}
      --build-arg UCS_VERSION=${UCS_VERSION}


build-ucs-base-dev-50X-matrix:
  stage: build
  extends: .kaniko
  needs: []
  parallel:
    matrix:
      - UCS_VERSION:
          - 500
          - 501
          - 502
          - 503
          - 504
          - 505
  variables:
    APT_REPOSITORY: "http://updates.knut.univention.de/"
    KANIKO_BUILD_CONTEXT: "docker"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-dev-${UCS_VERSION}"
    KANIKO_ARGS:
      --build-arg UCS_VERSION=${UCS_VERSION}
      --build-arg APT_REPOSITORY=${APT_REPOSITORY}
      --target dev

test-ucs-base-dev-usage-example:
  stage: build
  extends: .kaniko
  needs:
    - job: build-ucs-base-dev-50X-matrix
      artifacts: true
  parallel:
    matrix:
      - UCS_VERSION:
          - 500
          - 501
          - 502
          - 503
          - 504
          - 505
  variables:
    KANIKO_BUILD_CONTEXT: "docker"
    DOCKERFILE_PATH: "docker/dev.Dockerfile.usage-example"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-dev-usage-example"
    KANIKO_CACHE_ARGS: ""
    KANIKO_ARGS:
      --no-push
      --build-arg UCS_BASE_IMAGE_TAG=${BUILD_VERSION}
      --build-arg UCS_VERSION=${UCS_VERSION}

build-ucs-base-test-dev-510:
  stage: build
  extends: .kaniko
  needs: []
  variables:
    UCS_VERSION: 510
    APT_REPOSITORY: "http://updates-test.software-univention.de/"
    KANIKO_BUILD_CONTEXT: "docker"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-test-${UCS_VERSION}-dev"
    KANIKO_ARGS:
      --build-arg UCS_VERSION=${UCS_VERSION}
      --build-arg APT_REPOSITORY=${APT_REPOSITORY}
      --target dev

build-ucs-base-test-dev-520:
  stage: build
  extends: .kaniko
  needs: []
  variables:
    UCS_VERSION: 520
    APT_REPOSITORY: "http://updates-test.software-univention.de/"
    KANIKO_BUILD_CONTEXT: "docker"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-test-${UCS_VERSION}-dev"
    KANIKO_ARGS:
      --dockerfile usr-merge.Dockerfile
      --build-arg UCS_VERSION=${UCS_VERSION}
      --build-arg APT_REPOSITORY=${APT_REPOSITORY}
      --target dev

test-ucs-base-test-dev-usage-example:
  stage: build
  extends: .kaniko
  needs:
    - job: build-ucs-base-test-dev-510
      artifacts: true
    - job: build-ucs-base-test-dev-520
      artifacts: true
  parallel:
    matrix:
      - UCS_VERSION:
          - 510
          - 520
  variables:
    KANIKO_BUILD_CONTEXT: "docker"
    DOCKERFILE_PATH: "docker/test-dev.Dockerfile.usage-example"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ucs-base-test-dev-usage-example"
    KANIKO_CACHE_ARGS: ""
    KANIKO_ARGS:
      --no-push
      --build-arg UCS_BASE_IMAGE_TAG=${BUILD_VERSION}
      --build-arg UCS_VERSION=${UCS_VERSION}

changelog:
  image:
    name: orhunp/git-cliff:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: clone # clone entire repo instead of reusing workspace
    GIT_DEPTH: 0 # avoid shallow clone to give cliff all the info it needs
  stage: package
  script:
    - |
      apt update && apt install -y git
      git-cliff -c cliff.toml -o CHANGELOG.md
      git add CHANGELOG.md
      if [ -n $GIT_COMMIT_TAG]; then git commit -m "chore(release): $CI_COMMIT_TAG"; else echo "Not creating a release in the changelog"; fi
      git push origin HEAD:$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - CHANGELOG.md

...
