---

# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.40.4"
    file:
      - "defaults/stages.yaml"
      - "defaults/nubus-workflow.yaml"
      - "templates/kaniko.yaml"
      - "templates/harbor.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/lint-pre-commit.yaml"

stages:
  - "prepare"
  - "build"
  - "post-build"
  - "test"
  - "trigger"
  - "package"
  - "publish"
  - "deploy"
  - "lint"

variables:
  EXTERNAL_REGISTRY: "docker.software-univention.de"
  TEST_DATE_BASED_TAGGING:
    description: >-
      Set to "true" in order to run the date based tagging job on a branch.
      Mainly intended to support testing the pipeline itself.
    value: "false"
    options:
      - "true"
      - "false"

.post-build-matrix: &post-build-matrix
  - IMAGE_BASENAME:
      - "ucs-base"
    UCS_VERSION:
      - 5010
      - 520
      - 521

container-build:
  # The GitLab runner mounts the Docker socket into /var/run.
  # Kaniko either ignores /var/run (default), or the socket ends up in the tarball.
  # We unmount the socket here, and later use `--ignore-var-run=false` to have a
  # regular /var/run directory in the final image.
  before_script:
    - "umount /var/run/docker.sock"
    - "rm -rf /var/run"
  parallel:
    matrix:
      - IMAGE_BASENAME: "ucs-base"
        UCS_VERSION:
          - 5010
        APT_REPOSITORY: "http://updates.software-univention.de/"
        TARGET: "final-with-packages"
      - IMAGE_BASENAME: "ucs-base"
        UCS_VERSION:
          - 520
          - 521
        APT_REPOSITORY: "http://updates.software-univention.de/"
        TARGET: "final-with-packages"
        DOCKERFILE_PATH: "usr-merge.Dockerfile"
      - IMAGE_BASENAME: "ucs-base-python"
        UCS_VERSION:
          - 520
          - 521
        APT_REPOSITORY: "http://updates-test.software-univention.de/"
        TARGET: "final-with-packages-and-python"
        DOCKERFILE_PATH: "usr-merge.Dockerfile"
      - IMAGE_BASENAME: "ucs-base-dev"
        UCS_VERSION:
          - 5010
        APT_REPOSITORY: "http://updates.software-univention.de/"
        TARGET: "dev"
      - IMAGE_BASENAME: "ucs-base-dev"
        UCS_VERSION:
          - 520
          - 521
        APT_REPOSITORY: "http://updates-test.software-univention.de/"
        TARGET: "dev"
        DOCKERFILE_PATH: "usr-merge.Dockerfile"
  variables:
    KANIKO_BUILD_CONTEXT: "docker/ucs-base"
    IMAGE_NAME: "${IMAGE_BASENAME}-${UCS_VERSION}"
    KANIKO_ARGS: --ignore-var-run=false
      --build-arg UCS_VERSION=${UCS_VERSION}
      --build-arg APT_REPOSITORY=${APT_REPOSITORY}
      --target ${TARGET}


container-add-date-based-tags:
  stage: post-build
  extends: .skopeo
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: "$CI_MERGE_REQUEST_DESCRIPTION =~ /force-date-based-tags/"
    - if: $TEST_DATE_BASED_TAGGING == "true"
  variables:
    GIT_STRATEGY: none
    UCS_VERSIONS: 5010 520 521
  script:
    - |
      tag_image() {
        local image_prefix=$1
        local ucs_version=$2
        local source_image="$CI_REGISTRY_IMAGE/${image_prefix}-${ucs_version}:$RELEASE_VERSION"
        local target_image="${source_image}-build-$(date -I)"
        echo "Tagging image"
        echo "  from: $source_image"
        echo "    to: $target_image"
        /bin/skopeo copy docker://$source_image docker://$target_image
      }

      for ucs_version in $UCS_VERSIONS; do
        tag_image "ucs-base" "$ucs_version"
      done

      for ucs_version in 520 521; do
        tag_image "ucs-base-python" "$ucs_version"
      done


test-ucs-base-usage-example:
  stage: "test"
  extends: ".kaniko"
  cache: null
  parallel:
    matrix:
      - IMAGE_BASENAME: "ucs-base"
        DOCKERFILE_PATH: "Dockerfile.usage-example"
        UCS_VERSION:
          - 5010
          - 520
          - 521
      - IMAGE_BASENAME: "ucs-base-dev"
        DOCKERFILE_PATH: "dev.Dockerfile.usage-example"
        UCS_VERSION:
          - 5010
          - 520
          - 521
  variables:
    KANIKO_BUILD_CONTEXT: "docker/ucs-base"
    IMAGE_NAME: "${IMAGE_BASENAME}-${UCS_VERSION}"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/${IMAGE_BASENAME}-${UCS_VERSION}-usage-example"
    KANIKO_CACHE_ARGS: ""
    KANIKO_ARGS: --no-push
      --build-arg UCS_BASE_IMAGE_TAG=${RELEASE_VERSION}
      --build-arg UCS_VERSION=${UCS_VERSION}

mirror-release:
  stage: "publish"
  image: "${RUNNER_REGISTRY_IMAGE}:${RUNNER_IMAGE_TAG}"
  variables:
    RUNNER_REGISTRY_IMAGE: "gitregistry.knut.univention.de/univention/infrastructure/ci-images/gitlab-utils/gitlab-utils"
    RUNNER_IMAGE_TAG: "latest"
  parallel:
    matrix:
      - UCS_VERSION:
          - 5010
          - 520
          - 521
  script:
    - |
      set -eu
      # check if RELEASE_VERSION is a release version, not a pre-release version
      MATCH="^[0-9]+\.[0-9]+\.[0-9]+$";
      if [[ "${RELEASE_VERSION}" =~ ${MATCH} ]]; then
        echo "Release version '${RELEASE_VERSION}' detected, mirroring '$CI_REGISTRY_IMAGE/ucs-base-$UCS_VERSION:$RELEASE_VERSION' to '$PUBLIC_DOCKER_REGISTRY/ucs-base-$UCS_VERSION:$RELEASE_VERSION'"
      else
        echo "No valid release version detected (RELEASE_VERSION is '${RELEASE_VERSION}'), skipping mirroring"
        exit 0
      fi
      chmod 0400 "${DOCKER_PROXY_MACHINE_SSH_KEY}"
      export SSH_CMD="ssh -i ${DOCKER_PROXY_MACHINE_SSH_KEY} -o UserKnownHostsFile=\"${DOCKER_PROXY_MACHINE_SSH_PUBLIC_KEY}\""
      ${SSH_CMD} "${DOCKER_PROXY_USER}"@"${DOCKER_PROXY_MACHINE}" sudo /usr/bin/docker \
        pull \
        "${CI_REGISTRY_IMAGE}/ucs-base-${UCS_VERSION}:${RELEASE_VERSION}"
      ${SSH_CMD} "${DOCKER_PROXY_USER}"@"${DOCKER_PROXY_MACHINE}" sudo /usr/bin/docker \
        tag \
        "${CI_REGISTRY_IMAGE}/ucs-base-${UCS_VERSION}:${RELEASE_VERSION}" \
        "${PUBLIC_DOCKER_REGISTRY}/ucs-base-${UCS_VERSION}:${RELEASE_VERSION}"
      ${SSH_CMD} "${DOCKER_PROXY_USER}"@"${DOCKER_PROXY_MACHINE}" sudo /usr/bin/docker \
        push \
        "${PUBLIC_DOCKER_REGISTRY}/ucs-base-${UCS_VERSION}:${RELEASE_VERSION}"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

...
