---

# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      # "Check for added large files"
      - id: check-added-large-files
      # "Check for merge conflicts"
      - id: check-merge-conflict
      # "Check Yaml"
      - id: check-yaml
        args:
          # Allow custom tags like Gitlab's "!reference" tag.
          - --unsafe
        exclude: ^helm/.+/templates/
      # "Fix python encoding pragma"
      # - id: fix-encoding-pragma
      # "Trim Trailing Whitespace"
      - id: trailing-whitespace

# "Commit messages"
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v3.0.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

# "Ruff Python linter"
  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    rev: "v0.1.9"
    hooks:
      - id: "ruff"
        alias: "ruff-check"
        name: "ruff check"
        args: ["--ignore=TD002,TD003,FIX002"]
      - id: "ruff"
        alias: "ruff-fix"
        name: "ruff fix"
        stages: ["manual"]
        args: ["--fix", "--ignore=TD002,TD003,FIX002"]

# "Black Python formatter"
  - repo: https://github.com/psf/black
    rev: "23.12.0"
    hooks:
      - id: black

# "Shell Syntax Check"
# This is a wrapper for shellcheck as long as
# shellcheck doesn't have it's own .pre-commit-hooks.yaml
# https://github.com/koalaman/shellcheck/pull/1032
#- repo: https://gitlab.com/univention/pre-commit-hooks/pre-commit-shell
#  rev: v1.0.6
#  hooks:
#  - id: shell-lint

# "docker-compose.yaml linter"
  - repo: https://gitlab.com/univention/pre-commit-hooks/docker-compose-check
    rev: 7702a8801a158b8595569dd29e2dd655d8a08310
    hooks:
      - id: docker-compose-check

# "Dockerfile linter"
  - repo: https://gitlab.com/univention/pre-commit-hooks/docker-pre-commit
    rev: v2.0.0
    hooks:
      - id: hadolint-system
        args:
          - --ignore
          - DL3059
          - --ignore
          - DL3008
          # We need to keep the package lists to allow reproducible builds downstream
          - --ignore
          - DL3009

  - repo: "https://git.knut.univention.de/univention/dist/pre-commit-hooks/addlicense"
    rev: "v1.0.1"
    hooks:
      - id: "addlicense"
        name: "Check or add license headers to files"

...
