---
branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
      changelogTitle: "# Changelog"
  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - - "@semantic-release/gitlab"
    - assets:
      - path: "CHANGELOG.md"
        label: "CHANGELOG"
      - path: "sbom*"
      - path: "gl-code-quality-report*"
...
