branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/gitlab"
