ARG UCS_BASE_IMAGE_TAG=latest
ARG UCS_VERSION=506

FROM gitregistry.knut.univention.de/univention/components/ucs-base-image/ucs-base-${UCS_VERSION}:${UCS_BASE_IMAGE_TAG}

RUN apt-get update \
    && apt-get --assume-yes --verbose-versions --no-install-recommends install \
      python3-univention-config-registry \
    && rm -fr /var/lib/apt/lists/* /var/cache/apt/archives/*
